Video transcoding api setup
Educado-App/educado-backend pull request #103
Opened 2023-11-10 11:50 UTC by Vagn99

## Description

We have changed the GCP handling routes, so they are now using the new video/transcoding service.

## Changes

All of the routes now basically just forwards requests to the video/transcoding service.

## Related Issues

NIL

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

NIL

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

This will break the loading of images and videos on the front end until this commit from the front end has been merged into its dev:

Branch: staging

Commit id: 48301bf

## Notes for Reviewers

Please just test the routes locally in Postman :)

2023-11-10 14:50 UTC, Donhusum approved these changes

2023-11-11 18:31 UTC, Havkost requested changes
## Changes requested
Lille ændring + overvejelse ift. senere error handling

2023-11-11 18:31 UTC, Havkost commented on routes/bucketRoutesGCP.js
> +const serviceUrl = "https://video-service-staging-x7rgvjso4a-ew.a.run.app/";
Fjern ekstra / sidst i URL'en.
Måske den burde rykkes til en environment fil ell.lign?

2023-11-13 08:43 UTC, sofiiagran commented on routes/bucketRoutesGCP.js
> +    res.send("Error: " + error);
Skal man ikke bruge error codes ?

2023-11-13 08:44 UTC, sofiiagran commented on routes/bucketRoutesGCP.js
> +    res.send("Error: " + error);
måske lave en try catch i stedet?

2023-11-13 09:56 UTC, Vagn99 commented on routes/bucketRoutesGCP.js
> +const serviceUrl = "https://video-service-staging-x7rgvjso4a-ew.a.run.app/";
Den er rykket til .evn nu!

2023-11-14 08:19 UTC, JackSMunn submitted a review, later dismissed

2023-11-14 08:20 UTC, JackSMunn approved these changes
I approve, if the changes @Havkost has requested are completed.

2023-11-15 11:04 UTC, Vagn99 commented on routes/bucketRoutesGCP.js
> +    res.send("Error: " + error);
Der er styr på errors nu 😎
<img width="571" alt="image" src="https://github.com/Educado-App/educado-backend/assets/92516401/90987bf7-7101-4611-86cb-b9866d35bcf1">

2023-11-15 11:04 UTC, Vagn99 commented on routes/bucketRoutesGCP.js
> +const serviceUrl = "https://video-service-staging-x7rgvjso4a-ew.a.run.app/";
<img width="410" alt="image" src="https://github.com/Educado-App/educado-backend/assets/92516401/262effb4-ea35-4e60-b7f5-21c2c65e190c">

2023-11-21 11:41 UTC, merged