Gamified leaderboard (#107)
Educado-App/educado-backend pull request #108
Opened 2023-11-16 11:48 UTC by Mafusn

## Description

Added a route for fetching the top 100 students for day, week, month and overall.

## Changes

- Added a route for fetching the top 100 students for day, week, month and overall.
- Created test for the route
- Created a new errorCode for giving a wrong time interval

## Related Issues

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Notes for Reviewers

Please just test the routes locally in Postman :)

2023-11-21 10:03 UTC, JackSMunn requested changes
Nothing major, just address it, might not need changes

2023-11-21 10:03 UTC, JackSMunn commented on routes/studentRoutes.js
> +const { findTop100Students } = require('../helpers/leaderboard');
should you be able to see yourself in comparison to the top 100 on the leaderboard?

2023-11-21 13:12 UTC, MortenMunk requested changes
I noticed a small thing about the tests, as they only test if the response is an array, and not if the array contains the correct elements, or just  a single correct element/object.

I will let this be up to the PR owner, as it is a very small thing. Otherwise my comment can be resolved 😄 

Other than that, code looks good 👍 🥇

2023-11-21 13:12 UTC, MortenMunk commented on __tests__/routes/studentRoutes.test.js
> +    expect(response.body).toBeInstanceOf(Array);
The tests only check if the response is an array. Maybe it would be nice to check if the array contains at least one of the correct objects 😄

2023-11-22 08:30 UTC, Mafusn commented on __tests__/routes/studentRoutes.test.js
> +                pointsGiven: 10
It's only used here, and will mess up other tests

2023-11-22 08:54 UTC, merged