Gamified fix logic with is complete issue fix
Educado-App/educado-backend pull request #128
Opened 2023-11-26 14:30 UTC by loui981c

## Description

Addressing the problem where only exercise components inside the swiper had isComplete set to true has been resolved. Now, all components are updated, and the swiper starts at the first incomplete component, if any, instead of the start. Additionally, there is a refactoring of the points logic, but the underlying logic remains unchanged.
Changes

## Changes
The changes are related to issue from mobile [#199](https://github.com/Educado-App/educado-mobile/issues/199)

## Related Issues

Issue https://github.com/Educado-App/educado-mobile/issues/199

## Checklist

- [X] Code has been tested locally and passes all relevant tests.
- [X] Documentation has been updated to reflect the changes, if applicable.
- [X] Code follows the established coding style and guidelines of the project.
- [X] All new and existing tests related to the changes have passed.
- [X] Any necessary dependencies or new packages have been properly documented.
- [X] Pull request title and description are clear and descriptive.
- [X] Reviewers have been assigned to the pull request.
- [X] Any potential security implications have been considered and addressed.
- [X] Performance impact of the changes has been evaluated, if relevant.

## Notes for Reviewers

I have commented out some of the tests since the functions do not exist and they can't be found in the current dev branch. Please test with a new user and the third section of the course Finance

2023-11-26 21:37 UTC, sofiiagran requested changes
It looks like a lot of the tests fail? Plus it uses like 9 hours to test..?

2023-11-27 09:18 UTC, Mafusn commented on helpers/answerExercises.js
Why is this deleted?

2023-11-27 09:21 UTC, loui981c commented on helpers/answerExercises.js
all the functionality is in one place now in the file "completing.js"

2023-11-27 09:21 UTC, loui981c commented on helpers/pointSystem.js
all the functionality is in one place now in the file "completing.js"

2023-11-28 08:33 UTC, Jatewo commented
Failing tests and merge conflicts. Is this PR supposed to be closed?

2023-11-28 09:00 UTC, closed without merging