Vt merge
Educado-App/educado-backend pull request #130
Opened 2023-11-26 22:46 UTC by SlovenlyTF

## Description

Minor bug fixed surrounding: 
estimatedHours value 
Lectures
Components
status 
Exercise
Add som error codes 
 E11 - Component Errors

## Changes

- Minor bug fixed surrounding: 
- estimatedHours value 
- Lectures
- Components
- status 
- Exercise
- Add som error codes
- E11 - Component Errors

## Checklist

- [ ] Code has been tested locally and passes all relevant tests.
- [ ] Documentation has been updated to reflect the changes, if applicable.
- [ ] Code follows the established coding style and guidelines of the project.
- [ ] All new and existing tests related to the changes have passed.
- [ ] Any necessary dependencies or new packages have been properly documented.
- [ ] Pull request title and description are clear and descriptive.
- [ ] Reviewers have been assigned to the pull request.
- [ ] Any potential security implications have been considered and addressed.
- [ ] Performance impact of the changes has been evaluated, if relevant.

2023-11-26 22:47 UTC, SlovenlyTF commented
We it's failing... We've been trying to make it work all day, and need to run it past gamefied, to see how we can fix it.

2023-11-27 10:24 UTC, MortenMunk requested changes
Some minor changes requested... I did not run the code locally, and some of the code I am not familiar with, but all in all it looks fine, except for the comments 👍 🥇

2023-11-27 10:24 UTC, MortenMunk commented on __tests__/routes/courseRoutes.test.js
> +        console.log(response);
😢 Please remove console.log

2023-11-27 10:36 UTC, magnemo commented on __tests__/routes/courseRoutes.test.js
> +        console.log(response);
Has been done

2023-11-27 10:39 UTC, Mafusn approved these changes
Looks good

2023-11-27 11:13 UTC, MortenMunk approved these changes
Approving, as long as moving of error messages does not cause problems for other groups 👍 🥇

2023-11-27 11:28 UTC, PrometheusBork approved these changes
Looks fine and works with mobile dev for me, but I have a question. 
What is it that you are doing with "estimatedHours"? are you removing it? @SlovenlyTF

2023-11-27 13:07 UTC, merged