Onboarding login signup
Educado-App/educado-backend pull request #31
Opened 2023-10-05 20:51 UTC by MGLarsenSW

courseRoutes.js should match the Virtual Tutor teams file. Login is working so either remove the comment about it not working or it should be implemented correctly

2023-10-06 06:47 UTC, JackSMunn commented
Not following Pull request template found in resources. Make it draft and re-open when you have.

2023-10-06 08:47 UTC, Adachigaming commented
The failed tests are a result of old code not being runnable anymore, due to the new code changing the structure of the code.

2023-10-06 09:38 UTC, JackSMunn commented
Still not following PULL_REQUEST_TEMPLATE found in resources repo. Please follow the agreed upon guidelines for making a pull request.

2023-10-06 09:45 UTC, Jatewo commented
> The failed tests are a result of old code not being runnable anymore, due to the new code changing the structure of the code.

Make sure you have the newest commits from dev, since our tests run fine on that branch. If the problem persists, the problem is likely in your tests. Marking as draft, since you are not following the template and do not pass the tests.

2023-10-06 10:16 UTC, Adachigaming commented
### Description
This pull request is the complete backend functionality of the relevant PBIs of the Onboarding team.

### Changes
Added new routing for Login and Signup post requests: they are now handled in credentialsRoutes.js.
Changed the models of the ContencCreators to match the newer specifications, i.e. removed "motivation" and made "firstname" and "lastname" one field.
Added token creation upon receiving a login POST request in credentialsRouts.js, which the frontend is able to make use of,
Added hashing of password, which are handled in credentialsRoutes.js.
Added error messages that the frontend login page can use when invalid credentials are used, also in credentialsRouts.js.

Additionally, there are no new dependencies.

### Related Issues
There are no related issues to the above functionalities.

### Checklist

- [] Code has been tested locally and passes all relevant tests.
- [ ] Documentation has been updated to reflect the changes, if applicable.
- []  Code follows the established coding style and guidelines of the project.
- [ ] All new and existing tests related to the changes have passed.
- []  Any necessary dependencies or new packages have been properly documented.
- []  Pull request title and description are clear and descriptive.
- [ ]  Reviewers have been assigned to the pull request.
- []  Any potential security implications have been considered and addressed.
- [ ]  Performance impact of the changes has been evaluated, if relevant.
### Notes for Reviewers

2023-10-08 19:15 UTC, SlovenlyTF requested changes
There are a few things that need to be looked at, but the code in general seems good!👍
Mostly some merge errors of overwriting code, but I have a good way to fix them if you would like some help😊

2023-10-08 19:15 UTC, SlovenlyTF commented on routes/credentialsRoutes.js
> +router.post("/signup", async (req, res) => {
Above this function should be a doxygen comment. If you haven't used those before I'll give a quick summation, but you should read up on it a bit as well. It's a great way to make function comments or comments on larger bits of code, (and it's one of the guidelines we put into definition of done😉).

They're really easy to make with co-pilot, or with "Doxygen Documentation Generator" extension (though that one can be a bit finicky when the function is set up like this and not like a classic function).

The comment would look something like this for this code:
/**
 \* Signup Route.
 \* Creates a new Content Creator Application.
 \* 
 \* @param {JSON} Form Which includes the following fields:
 \*  @param {String} name Name of the Content Creator
 \*  @param {String} email Email of the Content Creator (Will be used for login)
 \*  @param {String} password Password of the Content Creator (Will be encrypted)
 \* @returns {JSON} Returns the created Content Creator Application
 */

You basically type in "/**" press enter and it does the rest.


/**
\* "Description"
\* 
\* "params" if applicable
\* "return value" if applicable
*/ 

But there is more to it, so take a skim through the wiki page😅

2023-10-08 19:15 UTC, SlovenlyTF commented on routes/credentialsRoutes.js
> +router.post("/login", async (req, res) => {
Along the same lines as the comment above😅

2023-10-08 19:15 UTC, SlovenlyTF commented on routes/index.js
I see multiple deleted routes. I get that you are adding the CredentialsRoutes, but I think you accidentally overwrote the other routes from the other teams. I think it's a simple merge error rather than an intentional change, but still good to keep an eye on.

2023-10-08 19:24 UTC, Adachigaming commented on routes/index.js
It seems that the `api/test` and `api/user` have been deleted. Like some other conflicts here, they are a result of us mistakenly thinking that a `User` pertained to `ContentCreators`. 
Therefore, these two routs should be kept.

2023-10-08 19:25 UTC, Adachigaming commented on routes/credentialsRoutes.js
We have discussed this, and will add more comments in future sprints.

2023-10-08 19:31 UTC, Adachigaming commented on models/User.js
This change should not be merged to dev, as these changes were again a mistake on our part.

2023-10-08 19:35 UTC, Adachigaming commented on .gitignore
> -config/keys.js
If they have figured out a solution, or improvement, that clashes with this code, we are fine with undoing this change.

2023-10-08 19:39 UTC, Adachigaming commented on config/keys.js
> -	TOKEN_SECRET: process.env.TOKEN_SECRET,
Perhaps a result of old code not mixing well with the new. I honestly forgot why we removed it, so I think keeping it would be fine.

2023-10-13 07:29 UTC, sofiiagran commented on .gitignore
> -config/keys.js
these files should not be removed from gitignore

2023-10-13 07:29 UTC, sofiiagran commented on config/keys.js
> -	TOKEN_SECRET: process.env.TOKEN_SECRET,
this should NOT be removed

2023-10-13 07:32 UTC, sofiiagran commented
I would recommend to comment out the code that gives you error from last year and that are not in use to make sure that the github action tests pass, no pull request can be accepted before all tests passed

2023-10-13 07:45 UTC, sofiiagran requested changes
Be careful when removing code written in dev. When you merge you should make sure to not remove code from dev on files not related to your work, ex. gitignore, keys, courses.js, user.js and index.js. Please fix this. Also make sure that github actions test pass. 

I also miss some tests.

When you go to the __test__ file you can see how you can conduct unit tests on your code.

2023-10-13 07:45 UTC, sofiiagran commented on config/keys.js
> -	TOKEN_SECRET: process.env.TOKEN_SECRET,
TOKEN_SECRET is important

2023-10-13 07:45 UTC, sofiiagran commented on routes/authRoutes.js
does this not create conflict with the code written in dev by the cert group?

2023-10-13 07:45 UTC, sofiiagran commented on models/User.js
You should keep the schema created in dev, not push your own

2023-10-13 07:45 UTC, sofiiagran commented on routes/index.js
you should not delete routes used by other groups

2023-10-16 11:10 UTC, closed without merging