GET routes for courses + update of the course model
Educado-App/educado-backend pull request #41
Opened 2023-10-11 09:13 UTC by Jatewo

## Description

Added GET routes for courses and updated the course model. Ensured that a user can only access their own courses.

## Changes

- Added MongoDB test json file to .gitignore
- Added a route for fetching courses made by a specific user
- Reworked route to get all courses
- Reworked require login to ensure that user specific information can only be accessed by the user in question
- Added adminOnly middleware to check if user is an admin (this is a placeholder without any actual functionality for now)
- Added tests for the course routes
- Added _id to fake user (for tests)
- Added fakeCourses file for getting some mock courses for testing purposes
- Added tests for admin only routes
- Added tests for course routes when unauthorized
- Removed some invalid fields in courses model

## Related Issues

#40

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Notes for Reviewers

Admin only function is sort of a mock for now - added for easy lock on private routes.

2023-10-11 09:54 UTC, Jatewo commented on __tests__/setup/globalConfigMongo.json
Note that this has been added to .gitignore and has been deleted to stop tracking of the file. The file is automatically created or updated upon running npm test

2023-10-12 08:33 UTC, Mafusn commented on __tests__/fixtures/fakeUser.js
Why do you manually set the ObjectId?

2023-10-12 08:35 UTC, Mafusn commented on middlewares/adminOnly.js
Remove console.log?

2023-10-12 08:36 UTC, Mafusn commented on middlewares/requireLogin.js
> +  console.log("Params: ", req.params);
Remove again

2023-10-12 08:36 UTC, Mafusn commented on middlewares/adminOnly.js
> +  console.log("Params: ", req.params);
Remove this

2023-10-12 08:38 UTC, Mafusn commented on routes/courseRoutes.js
I know it's not you who made the post requests, but as you suggested earlier, and to follow the Microsoft API guidelines, update requests should be PATCH. Eventually look at userRoutes.js in dev

2023-10-12 08:38 UTC, Mafusn requested changes
Only got some minor changes.

2023-10-12 20:06 UTC, Havkost requested changes
## Changes requested
Nice, just needs error codes in responses and a couple console logs removed 👍

The endpoint comments are not relevant to this pull request, but they should be addressed in the integration team.

2023-10-12 20:06 UTC, Havkost commented on routes/courseRoutes.js
... also some of the endpoints like `/courses/delete_all` go wild

2023-10-13 08:38 UTC, Jatewo commented on __tests__/fixtures/fakeUser.js
That's a leftover. Oversight on my part. Removing it now.

2023-10-13 08:52 UTC, Jatewo commented on __tests__/fixtures/fakeUser.js
I did it to easily know the id without several queries to the db, but I have reworked it now to ensure that no duplicate ids will exist by inserting and querying it again.

2023-10-13 08:54 UTC, Jatewo commented on routes/courseRoutes.js
I completely agree. However, I haven't changed anything until now, since I was waiting for an actual agreement to be made in the integration team. I will change these for now.

2023-10-13 08:56 UTC, Jatewo commented on routes/courseRoutes.js
> ... also some of the endpoints like `/courses/delete_all` go wild

Yeah, we should probably remove it. I will leave it for now - at least it requires a login, so it shouldn't be reachable right now

2023-10-13 09:01 UTC, Jatewo commented on middlewares/requireLogin.js
> +  console.log("Params: ", req.params);
Removed. Resolving...

2023-10-13 09:01 UTC, Jatewo commented on middlewares/adminOnly.js
> +  console.log("Params: ", req.params);
Removed. Resolving...

2023-10-13 09:11 UTC, Jatewo commented on models/Courses.js
> +    enum: ['Math', 'Science', 'Finance', 'Language', 'Sustainability', 'Other'],
I think those changes have disappeared in the GitHub void 😆 

I have made the changes again

2023-10-13 09:16 UTC, Jatewo commented on middlewares/adminOnly.js
Agreed. I have updated the middlewares 👍

2023-10-13 09:43 UTC, TheMOHD3886 approved these changes
Looks good 👍

2023-10-13 11:34 UTC, Mafusn commented on helpers/errorCodes.js
Is it supposed to delete the new errorCodes?

2023-10-13 11:35 UTC, Mafusn commented on helpers/validation.js
Why is this file deleted, it moduralises the project because the validation functions are used multiple places.

2023-10-13 11:35 UTC, Mafusn commented on index.js
Remove the console.log

2023-10-13 11:36 UTC, Mafusn commented on middlewares/adminOnly.js
> +      return res.status(401).send({ error: 'You are not allowed to access this content!' });
Why is this not using an errorCode

2023-10-13 11:36 UTC, Mafusn commented on middlewares/requireLogin.js
> +        return res.status(401).send({ error: 'You are not allowed to access this content!' });
Again, not using error codes

2023-10-13 11:38 UTC, Mafusn commented on models/Exercises.js
Why is this deleted, we have it in the resources folder for models

2023-10-13 11:38 UTC, Mafusn commented on models/Sections.js
Is not aligned with the resources models description

2023-10-13 11:38 UTC, Jatewo commented on helpers/validation.js
Idk why it says deleted but I don't believe it has ever existed on this branch. Is that possible?

2023-10-13 11:38 UTC, Mafusn commented on models/User.js
Is not aligned with the resources models description

2023-10-13 11:40 UTC, Mafusn commented on routes/courseRoutes.js
This is not supposed to include course/courses in every file @sofiiagran has changed this earlier.

2023-10-13 11:40 UTC, Mafusn commented on routes/index.js
This is linked to the comment on courseRoutes.js

2023-10-13 11:41 UTC, Mafusn commented on routes/index.js
> -router.use('/api/courses', CourseRoutes);
This is linked to the courseRoutes.js

2023-10-13 11:42 UTC, Mafusn commented on routes/userRoutes.js
Why is so much being deleted from this file?

2023-10-13 11:43 UTC, Mafusn commented on users/user.js
Should include firstName and lastName

2023-10-13 11:45 UTC, Mafusn requested changes
I think there is a lot of changes that have to be made due to a recent merge from another pull request. So a lot of the stuff from this pull request are suggesting some deletions of functions and files which are not supposed to be deleted.

2023-10-13 11:46 UTC, Mafusn commented on helpers/validation.js
Yes, because of the merge from @sofiiagran's branch there is possible some files which are new to your branch

2023-10-13 12:30 UTC, sofiiagran commented
Hey, I can see that there a lot of changes that overwrites team offline's, we are the ones working with and using the course routes for front-end and have made updates in the back-end as well,  I would therefore like to review it before merging.

2023-10-13 12:32 UTC, Jatewo commented
I am aware that something has gone completely wrong with the GitHub tracking. I will close this PR and a new one will be coming ASAP. I will try to implement all requested changes from this PR for the first review in the new one.

2023-10-13 12:32 UTC, closed without merging