Answer exercises and point system
Educado-App/educado-backend pull request #56
Opened 2023-10-17 11:01 UTC by Mafusn

## Description
This pull request includes the implementation of the following PBIs:
[App Course] [Backend] As a waste picker, I want to be able to answer exercises
[App Course] Implement points in Database

## Changes

- UserModel changed
- One route for completing exercises added to userRoutes
- Route for giving points to user
- Level system implemented

## Related Issues

## Checklist

- [ ] Code has been tested locally and passes all relevant tests.
- [ ] Documentation has been updated to reflect the changes, if applicable.
- [ ] Code follows the established coding style and guidelines of the project.
- [ ] All new and existing tests related to the changes have passed.
- [ ] Any necessary dependencies or new packages have been properly documented.
- [ ] Pull request title and description are clear and descriptive.
- [ ] Reviewers have been assigned to the pull request.
- [ ] Any potential security implications have been considered and addressed.
- [ ] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

## Notes for Reviewers

2023-10-17 11:36 UTC, Jatewo requested changes
### Very nice work
Although I haven't gone through the tests line by line it seems well-tested and in general the code seems fine.

I have two overall things which I'd like fixed before approving (one of which is very minor):

1. The response code for an email not found upon login should not be 404 (see my comment on this)
2. A little rework is needed to adhere to the Microsoft convention in the courses/sections routes (see my comment on this)

Please take a look at the other comments as well. Great job! 😄

2023-10-17 11:36 UTC, Jatewo commented on models/Users.js
Looks like parts of this file is using double indentation (2x 2 space tab). Changes are not needed right now. We will have the Linting check up and running by the next sprint, so this should be fixed by then 👍

2023-10-17 14:16 UTC, Jatewo commented on routes/courseRoutes.js
I guess a deletion works 🤣

2023-10-17 14:31 UTC, JackSMunn requested changes
See comments. One breaking change that we have created a fix for, lets talk about it.

2023-10-17 14:31 UTC, JackSMunn commented on routes/userRoutes.js
> +      // Extracts the points and level fields from updateFields
This is something we need to look at before we can merge this branch. The current implementation on dev is not passing tests correctly with this implementation. We have created a fix for it, that needs implementing. (let us talk about it tomorrow. 18.10/2023

2023-10-18 07:49 UTC, JackSMunn approved these changes
Approved as my issues are addressed.

2023-10-18 07:50 UTC, Jatewo approved these changes

2023-10-18 07:51 UTC, merged