Cert login save user info
Educado-App/educado-backend pull request #64
Opened 2023-10-19 12:16 UTC by Havkost

## Description

Return first and last name as `userInfo` (was `user`) instead of name in login route

## Changes

- Return first and last name as `userInfo` (was `user`) instead of name in login route
- Removed legacy version of retrieving environment variables in keys.js.

## Related Issues

(#66 in educado-mobile)

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

None.

## Notes for Reviewers

Provide any additional information that could be useful for reviewers. This could include context about the problem being solved, implementation details, or anything else that might aid in the review process.

2023-10-20 07:46 UTC, Mafusn approved these changes
Looks good, remember to update the tests

2023-10-20 08:51 UTC, MortenMunk requested changes
I believe the config folder can be removed?

other than that, it looks good 👍 🥇

2023-10-20 08:51 UTC, MortenMunk commented on config/keys.js
I think this can be removed entirely?

2023-10-20 09:29 UTC, MaizeHH approved these changes

2023-10-24 07:35 UTC, MortenMunk approved these changes
Looks good 👍 🥇

2023-10-24 07:35 UTC, merged