Video pr
Educado-App/educado-backend pull request #77
Opened 2023-10-25 12:31 UTC by Vagn99

## Description

We have created routes for interacting with the GCP bucket(s) (including streaming video). We have also route for fetching lecture by id.

## Changes

NIL

## Related Issues

NIL

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

<img width="1238" alt="image" src="https://github.com/Educado-App/educado-backend/assets/92516401/c42f70b6-77a2-4871-9360-8e2241a212b0">

<img width="376" alt="image" src="https://github.com/Educado-App/educado-backend/assets/92516401/2a8ec617-6cbf-44f5-8c1e-2859c6a42ee7">

<img width="533" alt="image" src="https://github.com/Educado-App/educado-backend/assets/92516401/3ccdc33d-e462-4ff8-9ac0-25b406e1d04e">

## Notes for Reviewers
NIL

2023-10-25 13:02 UTC, Mafusn approved these changes
Looks good

2023-10-25 13:58 UTC, JackSMunn commented
Please update changes to reflect the changes you have made.

2023-10-25 20:06 UTC, Havkost requested changes
## Don't merge - serious security issues
Please see my comment 👍

2023-10-25 20:06 UTC, Havkost commented on routes/bucketRoutesGCP.js
This file has serious security issues! 😱👻🎃
Right now it is possible to write arbitrary files to and even overwrite existing files on the server running the backend.

---

**POC attack against the backend running on localhost:8888**
Upload a file with a fileName equal to the path of the file you want to overwrite, in this case index.js just outside the _temp_bucketFiles directory (test.png is an image, but you can overwrite with any data):
`curl -X POST -H "Content-Type: multipart/form-data" -F "file=@test.png" -F "fileName=../index.js" http://localhost:8888/api/bucket/upload`

This has created the file in the bucket.\
Now we just need to read the file, which will write it to the local server, in turn overwriting the existing index.js:
`curl localhost:8888/api/bucket/download?fileName=../index.js`

2023-10-26 08:22 UTC, Vagn99 commented on routes/bucketRoutesGCP.js
Should be fixed now! Please have a look🎉☀️

2023-10-26 18:43 UTC, Havkost commented on routes/bucketRoutesGCP.js
Are you able to upload files to the server? I'm getting an error that uniqueFileName is not defined. If I define uniqueFileName in the form data, it says fileName is not defined, and if I supply both it goes back to saying that uniqueFileName is not defined.
Let's have a look at this together tomorrow - I'll be at uni at around 12:30 👍

2023-10-27 14:11 UTC, Vagn99 commented on routes/bucketRoutesGCP.js
I found the error, try it now 😎

2023-10-30 07:46 UTC, sofiiagran commented
Looks good, but the dev branch has been updated since your PR was created. 
Please check and solve the new conflicts:))

2023-10-30 07:49 UTC, sofiiagran requested changes
Looks good, but the dev branch has been updated since your PR was created. 
Please check and solve the new conflicts:))

2023-10-30 09:36 UTC, merged