Cert user rework merge
Educado-App/educado-backend pull request #89
Opened 2023-11-01 14:36 UTC by Jatewo

## Description

A rework of the User model as seen in the MODELS.md in the resources repo. The user will now have two "subprofiles" pointing to it in the database - a student profile for the app, and a content-creator profile for web.

## Changes

- Deleted credentialsRoutes and ContentCreatorRoutes (+relating tests), as these are now redundant
- Added error codes (see resources repo)
- Moved ensureNewValues to validation.js
- Renamed ContentCreatorApplication to ContentCreator
- Removed basic user info from contentCreator model
- Created Student model for app users and moved all Student specific information to this model from User
- Made a reference to a baseuser for contentCreator and Student models
- Made small updates to authRoutes
- Made StudentRoutes and moved all Student specific routes to this file (these are accessed at '/api/students'
- Changed UserRoute to create basic profiles for Students and ContentCreators when registering as a user
- Updated /api/courses/creator/:id to find a creator via a baseUser id
- Updated ref in Courses
- Removed unused imports
- Updated fakeContentCreator to take baseUserId
- Added checks for id's validity and updated tests to check for this
- Removed some console.logs
- Updated courseRoutes tests to use the new user model

## Checklist

- [X] Code has been tested locally and passes all relevant tests.
- [X] Documentation has been updated to reflect the changes, if applicable.
- [X] Code follows the established coding style and guidelines of the project.
- [X] All new and existing tests related to the changes have passed.
- [X] Any necessary dependencies or new packages have been properly documented.
- [X] Pull request title and description are clear and descriptive.
- [X] Reviewers have been assigned to the pull request.
- [X] Any potential security implications have been considered and addressed.
- [X] Performance impact of the changes has been evaluated, if relevant.

## Notes for reviewers

Please check that your work works as intended. I have tried to change as little as possible but changes were required in quite a few places.

2023-11-02 12:14 UTC, Mafusn commented on __tests__/fixtures/fakeUser.js
> -        subscriptions: []
Why is this removed?

2023-11-02 12:16 UTC, Mafusn commented on models/ContentCreator.js
Name of file should be plural

2023-11-02 12:19 UTC, Mafusn requested changes
Small comments, looks good overall.

2023-11-02 13:18 UTC, Jatewo commented on __tests__/fixtures/fakeUser.js
> -        subscriptions: []
is no longer included in the User model

2023-11-02 13:20 UTC, Jatewo commented on models/ContentCreator.js
I don't think we have any guidelines for this but it is probably the easiest considering the API guidelines

2023-11-02 13:32 UTC, Jatewo commented on models/Students.js
Is this currently in Dev? I don't think I have changed anything (at least not on purpose). And to clarify: have we removed isComplete from courses and sections?

2023-11-03 08:14 UTC, Mafusn approved these changes

2023-11-06 08:43 UTC, JackSMunn commented
The base is changed to staging for whatever reason, so we need to change it back to dev

2023-11-07 08:51 UTC, merged